### ISSUE TITLE
recoverMissingLumis taking a long time

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#240]
as reported by @prozober this is indeed taking quite some time.
The missing lumisection analysis is quite fast. What takes some time is to load the information back to reqmgr through CouchCollection and CouchFileset
@amaltaro if you have a couple of words of suggestions on how to make it bulk update.
meanwhile I am running a more detailed timing profile

**Comment by amaltaro** [comment]
I think the recoverMissingLumis takes much longer because:
1. it cares about the file name AND its location (thus it has to fetch the block name and query that block location in phedex)
2. it might have to get the parent file and location as well
3. as you said, it has to upload different couchdocs for different file+location

**Comment by vlimant** [comment]
as far as I can tell, it's 3. taking much of everything

**Comment by vlimant** [comment]
until we get a bulk update for the fileSet, I have added multithreading in 2 places 
https://github.com/CMSCompOps/WmAgentScripts/commit/2ef1030fd76ef237ad68bf514caed489d3d84fb2
@amaltaro if you want to take a look
