### ISSUE TITLE
core option in actor

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WmAgentScripts#253]
@areinsvo making a GH so that we keep track of this.
looks like the "cores" option is not wired in actor.

can you please remind me why you copied the singleRecovery function from recoveror.py instead of importing it ?
please take a look there and try to import it, the core (NOTE core vs coreS) option is added already so that resubmit.py works 
FYI @prozober

**Comment by prozober** [comment]
https://github.com/CMSCompOps/WorkflowWebTools/issues/79

**Comment by areinsvo** [comment]
It was easier to copy singleRecovery, rather than import it, because of differences in the input. I wanted to have control over how things were being implemented. 
For example, in actor.py memory is given in the json as 'memory': '20000' to set the memory to 20000,  whereas for recoveror.py it would be 'mem-+1000' to increase the  memory by 1000. It was non-trivial to a) understand the recoveror format and b) translate the actor format to the recoveror format.

However, then we run into issues such as these, when they become out of sync. 

For now I will try to quickly add the multicore functionality to actor.py. Next week I can look into what changes are needed to import singleRecovery instead.

**Comment by prozober** [comment]
Hi @areinsvo, do you think we are close to using this option from the recovery tool?
@dabercro, I think we need to have something like https://github.com/CMSCompOps/WorkflowWebTools/issues/87#issuecomment-355056628 for this parameter and display the multicore value close to the textbox. It'd help me a lot!

**Comment by areinsvo** [comment]
@prozober I'll probably be ready to test the multicore functionality tomorrow.
