### ISSUE TITLE
Enable cloning without killing workflow? 

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#285]
Dima insisted again today that this should be possible. The output dataset version number could be changed to avoid the duplication. 

Motivation: This top-priority request https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_PPD-RunIISummer18GS-00005 is making no progress since it's only running at DESY, which is pretty full. We should be able to clone it to run in parallel at CERN without killing the one at DESY.

**Comment by vlimant** [comment]
Doing such thing will have a sever impact upstream in mcm last time I checked.
it also breaks the paradigm of one workflow valid per prepid (not counting ACDC).
You can always clone using resubmit.py and assigned by hand, but then it's outside of unified ; which is fine since we get one such very very rarely.
Maybe better to tackle the initial issue than forcing a disruptive design change.
