### ISSUE TITLE
Unified should check with DBS block first and then match with PhEDEx files

### ISSUE THREAD

**Issue by thongonary** [CMSCompOps/WmAgentScripts#310]
Instead of vice-versa, so that there will be fewer false alerts of file mismatch when PhEDEx blocks are still filling and not appearing in DBS.
Details are in https://its.cern.ch/jira/browse/CMSCOMPPR-3480

**Comment by vlimant** [comment]
@ticoann please elaborate since there isn't enough information here and there.
plus I think what you suggest will allow for an output to look "clean" while there are still missing files in one of the system ; which is a no go before starting to check sanity of output.
I'll refer to https://github.com/dmwm/WMCore/issues/8148 for fixing the issue at the source.
