### ISSUE TITLE
Issue with checkor 

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#321]
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIIFall17GS-00021

Workflow lies in assistance-manual even after having 4 completed ACDCs.

@SvenjaPflitsch can you please have a look?

**Comment by SvenjaPflitsch** [comment]
It does not look like it is a checkor issue per se. Looking at the Unified log I can find the following messages: 
inconsistent ACDC vlimant_ACDC1_task_BPH-RunIIFall17GS-00021__v1_T_180817_170118_1228
inconsistent ACDC vlimant_ACDC1_task_BPH-RunIIFall17GS-00021__v1_T_180817_170153_6508
inconsistent ACDC vlimant_ACDC1_task_BPH-RunIIFall17GS-00021__v1_T_180817_170201_3664
inconsistent ACDC vlimant_ACDC2_task_BPH-RunIIFall17GS-00021__v1_T_180907_142122_5840
inconsistent ACDC vlimant_ACDC2_task_BPH-RunIIFall17GS-00021__v1_T_180907_142131_8379
inconsistent ACDC vlimant_ACDC3_task_BPH-RunIIFall17GS-00021__v1_T_180910_114242_495
inconsistent ACDC vlimant_ACDC3_task_BPH-RunIIFall17GS-00021__v1_T_180910_114331_5456
inconsistent ACDC vlimant_ACDC4_task_BPH-RunIIFall17GS-00021__v1_T_180911_120608_7400

I need to look up in the code what this means exactly.

**Comment by SvenjaPflitsch** [comment]
The names of the ACDC outputs are not consistent with the names of the outputs from the original workflow: 
This is the output from the original workflow:  its v11-v3
"/BuToJpsiK_BMuonFilter_SoftQCDnonD_TuneCP5_13TeV-pythia8-evtgen/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v3/AODSIM", 

The ACDCs all have v11-v2 instead of v3 in the name, e.g.: 
/BuToJpsiK_BMuonFilter_SoftQCDnonD_TuneCP5_13TeV-pythia8-evtgen/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v2/AODSIM
