### ISSUE TITLE
ACDC submitted according to WTC console didn't generated another ACDC

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#322]
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIISummer15wmLHEGS-00013

According to WTC console, on the ACDC0, action was submitted but ACDC1 never got created. Also the WTC console shows ACDC0 in green which means action has been submitted on it.

@dabercro @amaltaro @SvenjaPflitsch @vlimant can you please have a look?

**Comment by vlimant** [comment]
the action is there in the console, for actor to come and work on https://vocms0113.cern.ch/getaction?days=15 but https://cms-unified.web.cern.ch/cms-unified//logs/actor/last.log the action is empty

http://cms-unified.web.cern.ch/cms-unified/showlog/?search=critical&module=actor&limit=50&size=1000

@dabercro ?

**Comment by dabercro** [comment]
Yeah, I think these happen when multiple workflows are acted on at the same time. I'm still not sure yet.

In my opinion, the best thing to do is for the actor to use defaults since there are no provided details. I think actor used to handle these tasks that way, but this was changed as I mentioned here: https://its.cern.ch/jira/browse/CMSCOMPPR-3281?focusedCommentId=2181777&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2181777

Whatever we decide, we won't have a fix immediately. In the meanwhile, it's safe to resubmit an action for ACDC0 with details.
