### ISSUE TITLE
Do not set primary_AAA for workflows with NO input dataset

### ISSUE THREAD

**Issue by amaltaro** [CMSCompOps/WmAgentScripts#601]
**Impact of the bug**
Unified and WMAgent

**Describe the bug**
As reported - a long time ago - in this WMCore github issue:
https://github.com/dmwm/WMCore/issues/6999

when `TrustSitelists` is enabled to `True`, the job factory and job submitter will assign all the sites in the `SiteWhitelist` (well, minus the SiteBlacklist) as a potential site for the job to run. Which means, jobs will be submitted to sites that do not really hold any of the pileup dataset (causing a massive amount of job failures in production).

**How to reproduce it**
Assigning this workflow:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_EGM-RunIISummer19UL16GEN-00009__v1_T_200605_142821_2480

with the same settings.

**Expected behavior**
Most of the fixes will have to be applied on the WMCore side. However, there is one immediate change that can be done in Unified to mitigate such problems. When Unified is going to assign workflows, it should only set `prymary_AAA` (equivalent to TrustSitelists in WMCore) to `True` if the workflow contains input dataset.

Starting in the upcoming CMSWEB production upgrade (July 7), workflow assignment will fail if `TrustSitelists=True` for workflows without any input dataset.

**Additional context and error message**
From the P&R slack channel, these are a few samples affected by this bug:
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_EGM-RunIISummer19UL16GEN-00006
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EGM-RunIISummer19UL16GEN-00009
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TRK-RunIISummer19UL16GEN-00002
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EGM-RunIISummer19UL16GEN-00011
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EGM-RunIISummer19UL16GEN-00001

**Comment by sharad1126** [comment]
@amaltaro do you mean to put `primary_AAA` always `True` is there is an input dataset?
Also, what is expected if there is no input dataset?

**Comment by sharad1126** [comment]
Also, not to forget, for the wf in question, the campaigns setup have the `primary_AAA` as `True` here:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L1242
and that's where unified gets it flag value.

**Comment by sharad1126** [comment]
Another thing I just noticed here if it reminds you of something @amaltaro 
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/assignor.py#L239

**Comment by amaltaro** [comment]
> @amaltaro do you mean to put primary_AAA always True is there is an input dataset?

no, I wanted to say that we should use whatever is defined in the campaign. However, if the workflow does not have an input dataset, this flag should be forced to `False`.

**Comment by sharad1126** [comment]
yeah I understand your point and I think that's how generally a campaign is setup too but I am not sure why `RunIISummer19UL16SIM` is having this flag then. @scarletnorberg  can you check this?

**Comment by amaltaro** [comment]
This change has just been pushed to testbed:
https://github.com/dmwm/WMCore/pull/9770

which means, starting on July 7 workflows might fail to get assigned.

If nobody is able to work on it this week, I'll have a look in the next Monday (but better not wait for me).

**Comment by sharad1126** [comment]
@amaltaro I am not sure what is expected here more than to re-check the campaigns as there is no issues in the assignment logic from the codebase as I checked all places where `primary_aaa` flag is set.

**Comment by amaltaro** [comment]
If campaigns are properly configured, and there is no possibility to have different workflows within the same campaign, where one requests for input dataset; while the other does not. Then yes, there is nothing to be implemented and this issue can be closed.

**Comment by scarletnorberg** [comment]
@sharad1126 and @amaltaro I am not sure what you want or what you are asking.

For example for this one: https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_JME-RunIISummer19UL18DIGI-00007__v1_T_200221_081733_8783 one of the issues initial thought was that the input that is not PU the GenSim "/QCD_Pt-15to7000_TuneCP5_Flat2018_13TeV_pythia8/RunIISummer19UL18SIM-pilot_106X_upgrade2018_realistic_v11_L1v1-v3/GEN-SIM" could also not be run remotely. Talking to @todor-ivanov we thought it was because of the "TrustSitelists": false,. Checking the campaign it has primaryAAA:True https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L1237-L1245

I was actually thinking the campaign was getting over written by the extension of the input file. Like Gen can be read remotely but Gen-Sim could not. This was the part that was confusing to me. 

If this is not related to what you are saying please rephrase the question.

**Comment by scarletnorberg** [comment]
Talking to @sharad1126 it has become more clear. I think the reason that the RunIISummer19UL16SIM and all RunIISummer19UL*SIM campaigns is because when the original submission happen I believe that only Gen was submitted then the rest of the chain. So at the time the Sim needed to have primary_AAA as true because of the input file being probably remote. There are probably some lingering WF's that may go through the system like this but computing has told ppd to run from Gen to miniAOD so that means that probably the primary_AAA can be turned to false. I am worried thought because campaigns like GS sometimes have pLHE as input and sometimes do not.

Although when I look at a GS campaign:
https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json#L637-L644
There does not seem to be any information about primary_AAA right?

**Comment by amaltaro** [comment]
Thanks
