### ISSUE TITLE
Remove phedex checks for NANOAOD* if wmagents stop injection to phedex

### ISSUE THREAD

**Issue by sharad1126** [CMSCompOps/WmAgentScripts#602]
**Impact of the new feature**
If the dataset is being injected to rucio only, then we need to remove our filemismatch checks between phedex and dbs to only rucio and dbs checks.

**Is your feature request related to a problem? Please describe.**
If we don't do this, then we might have problems in workflows getting stuck in file mismatches. 

**Describe the solution you'd like**
remove phedex checks for NANOAOD* in checkor script.

**Describe alternatives you've considered**
no alternatives. 

**Additional context**
@amaltaro @todor-ivanov @nsmith- you might want to keep us updated with this.

**Comment by sharad1126** [comment]
@todor-ivanov would be great to look into this inorder to announce the stuck nanoaod wfs if they are because of this.

**Comment by nsmith-** [comment]
I thought this was handled by #561 ?

**Comment by sharad1126** [comment]
@nsmith- that was to add consistency check for rucio as well but it doesn't removes the check for phedex, and if we have nanoaod only injecting to rucio and not to phedex, then this is needed.

**Comment by todor-ivanov** [comment]
@sharad1126 If there is no data in Phedex regarding a workflow, but everything is only in Rucio I would assume that the set of  blocks returned by phedexClient here [1] would be of length 0 and it will just enter like that the union of set of blocks from Rucio and Phedex here [2]. Which would simply not matter and we would still have the correct result. It can break the code only if phedexClient raises and exception in this call [3] due to tha lack of information in Phedex for the dataset in question. Have  you actually observed such errors?


[1]
https://github.com/CMSCompOps/WmAgentScripts/blob/f99c3a374d865bac2ea78e09f47b73bb80b8695b/Unified/checkor.py#L1030

[2]
https://github.com/CMSCompOps/WmAgentScripts/blob/f99c3a374d865bac2ea78e09f47b73bb80b8695b/Unified/checkor.py#L1032

[3]
https://github.com/CMSCompOps/WmAgentScripts/blob/f99c3a374d865bac2ea78e09f47b73bb80b8695b/phedexClient.py#L149

**Comment by todor-ivanov** [comment]
@sharad1126 

>  If we don't do this, then we might have problems in workflows getting stuck in file mismatches.

Have you actually found some workflows stuck like that. And if so did you debug them to the bottom to check if this is the actual cause for the workflow to be stuck.

Have you actually

**Comment by sharad1126** [comment]
we have ~100 wfs in filemismatch right now. either they are because of the issues in injection to rucio or because of some inconsistencies in rucio/dbs. This GH issue was something I wanted to make sure is not affecting those nanoaod in filemismatch and also I guess it's not clear from the messages in checkor if there is an issue in rucio or phedex as you never changed it but did the union and so transfer team doesn't knows if it is some issue in rucio or phedex. Would be great to stop checking phedex if we don't inject data to phedex anymore for nanoaod.

**Comment by todor-ivanov** [comment]
Have you checked manually any of those to see what Rucio & Phedex & Dbs tell about their datasets?

**Comment by sharad1126** [comment]
@todor-ivanov yes we checked 2-3 in every category and was reported all about the things to DM team.

**Comment by haozturk** [comment]
Phedex is dead now, no need to keep this issue.
