### ISSUE TITLE
Phedex2Rucio transition: filemismatch check between DBS and Phedex

### ISSUE THREAD

**Issue by haozturk** [CMSCompOps/WmAgentScripts#665]
**Impact of the new feature**
Depends on the chosen alternative.

**Is your feature request related to a problem? Please describe.**
Unified checkor module checks the number of files of each output dataset in DBS and Phedex and determines if there is a filemismatch between these services. If there is, then it waits for a grace period of two days. If the problem does not get solved by other parties, then it puts the workflow into `assistance-filemismatch` status and PnR manually checks the workflow and contact transfer team in order to resolve the issue. Here is an example workflow in this state:
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIIAutumn18NanoAODv7-04219
With the Phedex2Rucio transition, we have decide the fate of this functionality.

Main functionality can be seen at [1] and the phedex calls can been seen at [2,3,4].

**Describe the solution you'd like**
Although, it's DM team's responsibility to solve filemismatches, PnR should somehow get an alert for this one in order to make sure the proper execution of the workflows. Therefore, I would say we should get this functionality somehow. I see two options: 
1. Implement the same functionality with Rucio equivalent.
2. Discuss the possibility of getting this functionality from WMCore team.

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1067-L1111
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1019
[3] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1041
[4] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1081

**Describe alternatives you've considered**
Described above.

**Additional context**
@drkovalskyi @z4027163 @amaltaro @todor-ivanov Please feel free to comment if you have any suggestions.

**Comment by todor-ivanov** [comment]
Hi @haozturk , at the very bottom of this check, the list of filenames is already corrected with the filenames from datatasets already existing in Rucio [1]. Once Phedex is stopped, the full list is going to be still valid, only that  the contribution from Phedex will be 0 files. But you are correct, the code needs to be rewritten in order to express the information with the proper log messages and to also make it correctly expressed and properly readable against the new Data Management system. 

As of the Phedex calls, IIRC their equivalents from Rucio perspective should be in [2], or at least what ever is missing should be easy to be put there. 

[1] https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1087
[2] https://github.com/CMSCompOps/WmAgentScripts/blob/master/RucioClient.py

**Comment by haozturk** [comment]
Resolved with #680 So, closing.
